/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tombala;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author sozcu
 */
public class AsudeSozcuStartClass extends javax.swing.JFrame {

    /**
     * Creates new form Start
     */
    public AsudeSozcuStartClass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        arrayLogın = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        plAYER2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PLAYER1 = new javax.swing.JTextField();
        start = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(32770, 32767));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 35)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 216, 142));
        jLabel1.setText("                  BINGO GAME");

        arrayLogın.setBackground(new java.awt.Color(231, 198, 125));
        arrayLogın.setFont(new java.awt.Font("Sitka Text", 0, 24)); // NOI18N
        arrayLogın.setForeground(new java.awt.Color(0, 0, 0));
        arrayLogın.setText("Create your own card");
        arrayLogın.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        arrayLogın.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrayLogınActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(51, 153, 255));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField1.setText("PLAYER 1 NAME:");

        plAYER2.setBackground(new java.awt.Color(231, 198, 125));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("PLAYER 2  NAME:");

        PLAYER1.setBackground(new java.awt.Color(231, 198, 125));

        start.setBackground(new java.awt.Color(231, 198, 125));
        start.setFont(new java.awt.Font("Sitka Text", 0, 24)); // NOI18N
        start.setForeground(new java.awt.Color(0, 0, 0));
        start.setText("Start");
        start.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plAYER2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PLAYER1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(arrayLogın, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PLAYER1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plAYER2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arrayLogın, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    static AsudeSozcuPlayerClass player1 = new AsudeSozcuPlayerClass();
    static AsudeSozcuPlayerClass player2 = new AsudeSozcuPlayerClass();
    static JLabel[][] labels;
    static JLabel[][] labels2;

    public static int[][] card1;
    public static int[][] card2;

    public static int getNumber(String message) {
        String input = JOptionPane.showInputDialog(null, message);
        int number = 0;
        try {
            number = Integer.parseInt(input);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid input! Please enter a valid integer.");
            number = getNumber(message); 
        }
        return number;
    }

    private void arrayLogınActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrayLogınActionPerformed
        int[][] array = new int[3][9];

        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 9; j++) {
                array[i][j] = getNumber("Enter the value for position [" + i + "][" + j + "]:");

            }
        }

        int[][] array2 = new int[3][9];

        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 9; j++) {
                array2[i][j] = getNumber("Enter the value for position [" + i + "][" + j + "]:");

            }
        }

        card1 = array;
        card2 = array2;
        player1.name = PLAYER1.getText();
        player2.name = plAYER2.getText();
        AsudeSozcuGameClass newgame = new AsudeSozcuGameClass();
        AsudeSozcuBıngoMethodsClass generator = new AsudeSozcuBıngoMethodsClass();

        AsudeSozcuStartClass.player1.card = generator.arrayToMultiLinkedList(array);
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 9; j++) {
                if (card1[i][j] != -1) {
                    labels[i][j].setText(card1[i][j] + " ");

                } else {
                    Color customColor = new Color(255, 201, 74);
                    labels[i][j].setBackground(customColor);
                    labels[i][j].setOpaque(true);

                }
            }
        }
        AsudeSozcuStartClass.player2.card = generator.arrayToMultiLinkedList(array2);

        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 9; j++) {
                if (card2[i][j] != -1) {
                    labels2[i][j].setText(card2[i][j] + " ");

                } else {
                    Color customcolor = new Color(54, 84, 134);
                    labels2[i][j].setBackground(customcolor);

                    labels2[i][j].setOpaque(true);

                }
            }
        }
        this.dispose();
        newgame.setVisible(true);


    }//GEN-LAST:event_arrayLogınActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        player1.name = PLAYER1.getText();
        player2.name = plAYER2.getText();
        AsudeSozcuGameClass newgame = new AsudeSozcuGameClass();
        AsudeSozcuBıngoMethodsClass generator = new AsudeSozcuBıngoMethodsClass();
        newgame.generateforplayer1();
        newgame.generateforplayer2();

        generator.arrayToMultiLinkedList(card1);
        generator.arrayToMultiLinkedList(card2);
        this.dispose();
        newgame.setVisible(true);

    }//GEN-LAST:event_startActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsudeSozcuStartClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsudeSozcuStartClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsudeSozcuStartClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsudeSozcuStartClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsudeSozcuStartClass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PLAYER1;
    private javax.swing.JButton arrayLogın;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField plAYER2;
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables
}
